removed confusing logging in get memory handler
facebookresearch/droidlet pull request #202
Opened 2021-02-26 21:58 UTC by snyxan

# Description

The exception logging is confusing. so removed it.

Fixes #182 

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] Proposes a change (non-breaking change that isn't necessarily a bug)
- [ ] Refactor
- [ ] New feature (non-breaking change that adds a new functionality)
- [ ] Breaking change (fix or feature that would break some existing functionality downstream)
- [ ] This is a unit test
- [ ] Documentation only change

## Type of requested review

- [ ] I want a thorough review of the implementation.
- [ ] I want a high level review. 
- [ ] I want a deep design review.

# Testing

Tested locally

# Checklist:

- [ ] I have performed manual end-to-end testing of the feature in my environment.
- [ ] I have added Docstrings and comments to the code.
- [ ] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added relevant collaborators to review the PR before merge.

2021-02-26 22:36 UTC, anuragprat1k requested changes

2021-02-26 22:36 UTC, anuragprat1k commented on base_agent/dialogue_objects/get_memory_handler.py
> -            logging.exception(e)
I think it is useful to log this exception. Just prettify it perhaps?

2021-02-26 22:40 UTC, anuragprat1k commented
Generally, I think we should be logging exceptions since we don't throw them anyway. It is a useful debugging tool. Without it there's no easy way to find out what might be causing an exception. For example in this case, without the trace it would be hard to debug why `do_answer` might be failing.

2021-03-01 13:30 UTC, snyxan commented
> Generally, I think we should be logging exceptions since we don't throw them anyway. It is a useful debugging tool. Without it there's no easy way to find out what might be causing an exception. For example in this case, without the trace it would be hard to debug why `do_answer` might be failing.

Added exception logging back and caught IndexError separately. I believe Arthur deliberately throws index errors and let them caught by exception handler. In this way, agent can respond with 'I don't understand what you're asking'.

Since we want: 1. use IndexError as a way to respond with 'IDK', 2. still be able to catch&analyze other unpredictable errors, using two catching here to distinguish them.

2021-03-02 06:59 UTC, anuragprat1k approved these changes
Looks good except one comment that I've left inline.

2021-03-02 06:59 UTC, anuragprat1k commented on base_agent/dialogue_objects/get_memory_handler.py
> +        except IndexError: # index error indicates no answer available
Can you also add a logging statement for the `IndexError` here? We shouldn't be catching errors silently. Adding a logging statement here will help disambiguate the `ErrorWithResponse` thrown here from all the other places that `ErrorWithResponse` could arise from.

2021-03-02 11:20 UTC, merged