Added missing files in mephisto app
facebookresearch/droidlet pull request #244
Opened 2021-03-11 19:13 UTC by snyxan

# Description

Added those missing files in mephisto static html app. Deleted gitignore file which is the cause of the file missing issue.

Ref: https://github.com/facebookresearch/Mephisto/tree/master/examples/simple_static_task 

## Type of change

Please check the options that are relevant.

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] Proposes a change (non-breaking change that isn't necessarily a bug)
- [ ] Refactor
- [ ] New feature (non-breaking change that adds a new functionality)
- [ ] Breaking change (fix or feature that would break some existing functionality downstream)
- [ ] This is a unit test
- [ ] Documentation only change

## Type of requested review

- [ ] I want a thorough review of the implementation.
- [ ] I want a high level review. 
- [ ] I want a deep design review.

# Testing

Tested locally and passed.

# Checklist:

- [ ] I have performed manual end-to-end testing of the feature in my environment.
- [ ] I have added Docstrings and comments to the code.
- [ ] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [ ] New and existing unit tests pass locally with my changes.
- [ ] I have added relevant collaborators to review the PR before merge.

2021-03-11 22:21 UTC, Rebecca-Qian requested changes
Let's not check in data files. The current parameters are a placeholder for when we want to route job data. I added the `.gitignore` to avoid checking this in.

You can create the empty `extra_refs` directory, but can you add the `.gitignore` back? We can and should add to `README.md` instructions on how to populate the `data.csv` file.

2021-03-13 17:53 UTC, snyxan commented
> Let's not check in data files. The current parameters are a placeholder for when we want to route job data. I added the `.gitignore` to avoid checking this in.
> 
> You can create the empty `extra_refs` directory, but can you add the `.gitignore` back? We can and should add to `README.md` instructions on how to populate the `data.csv` file.

Done

2021-03-15 22:20 UTC, Rebecca-Qian commented
> > Let's not check in data files. The current parameters are a placeholder for when we want to route job data. I added the `.gitignore` to avoid checking this in.
> > You can create the empty `extra_refs` directory, but can you add the `.gitignore` back? We can and should add to `README.md` instructions on how to populate the `data.csv` file.
> 
> Done. Let's add instructions in a separate PR.

I still see `crowdsourcing/droidlet_static_html_task/data.csv` in the files modified by this PR.

2021-03-16 08:58 UTC, Rebecca-Qian approved these changes

2021-03-17 05:17 UTC, merged