[Dashboard][v0] Register subdomains to proxy HTTP content through Cloudflare
facebookresearch/droidlet pull request #265
Opened 2021-03-18 19:41 UTC by Rebecca-Qian

# Description

This PR registers a unique subdomain to *.craftassist.io on successful ECS container spinup. The subdomain acts as HTTP/HTTPS proxy and tunnels unencrypted content from the container IPs. 

PR also sets env variable in ECS containers to enable Cloudflare access. servermgr env variables are configured in Heroku.

Asked for a thorough review so people are familiar with dashboard changes.

Follow ups
- We'll migrate to a pool of pre-launched instances in v1, so that Turkers don't have to wait around for instance creation. The cloudflare logic in this PR will mostly remain the same, but we'll want to move this up to the Mephisto/MTurk layer.
-  Currently using Cloudflare account registered under my email; we might want to switch to team and get an enterprise account.

Please check the options that are relevant.

- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] Proposes a change (non-breaking change that isn't necessarily a bug)
- [ ] Refactor
- [x] New feature (non-breaking change that adds a new functionality)
- [ ] Breaking change (fix or feature that would break some existing functionality downstream)
- [ ] This is a unit test
- [ ] Documentation only change

## Type of requested review

- [x] I want a thorough review of the implementation.
- [ ] I want a high level review. 
- [ ] I want a deep design review.

## Before and After

If this PR introduces a change or fixes a bug, please add before and after screenshots (if this is causes a UX change) or before and after examples(this could be plain text, videos etc ) to demonstrate the change.

If this PR introduces a new feature, please also add examples or screenshots demonstrating the feature.

# Testing

Please describe the tests that you ran to verify your changes and how we can reproduce.

# Checklist:

- [x] I have performed manual end-to-end testing of the feature in my environment.
- [x] I have added Docstrings and comments to the code.
- [ ] I have made changes to existing documentation where needed.
- [ ] I have added tests that show that the PR is functional.
- [ ] New and existing unit tests pass locally with my changes.
- [x] I have added relevant collaborators to review the PR before merge.

2021-03-18 20:27 UTC, soumith requested changes

2021-03-18 20:27 UTC, soumith commented on crowdsourcing/servermgr/app.py
> +        zone_id = 'd2d53d14fffaecbfeb92e3e62f01607f'
definitely remove this before committing this PR and instead power it through an env variable

2021-03-18 20:27 UTC, soumith commented on crowdsourcing/servermgr/app.py
> +    subdomain_name = "dashboard-{}".format(randint(0, 10 ** 9))
randint can technically produce the same number twice in rare cases. So before doing `dns_records.post`, you have to check that the record doesn't exist (if it exists, choose a different random number)

2021-03-20 00:06 UTC, snyxan commented on crowdsourcing/servermgr/app.py
> +        cf = CloudFlare.CloudFlare(email='rebeccaqian@fb.com', token=cloudflare_token)
put email into env var instead of hardcoding.

2021-03-21 22:25 UTC, soumith approved these changes

2021-03-23 00:50 UTC, merged